### ISSUE TITLE
Solution Branch: "/" and "/(app)" routes conflict with each other error

### ISSUE THREAD

**Issue by CarlosGTrejo** [joysofcode/advanced-layouts#2] opened 2023-11-10 03:52 UTC
I tried to open the solution branch on Stackblitz, then right after cloning I got this error:
```
The "/" and "/(app)" routes conflict with each other
9:45:12 PM [vite] server restarted.
Failed to load url /.svelte-kit/generated/server/internal.js (resolved id: /.svelte-kit/generated/server/internal.js). Does the file exist?
```

I didn't change anything, just cloned the solution branch using Stackblitz and waited for it to launch.

**Comment by matiadev** [comment] 2023-12-10 17:30
The problem was caused by duplicate routes which should be fixed https://github.com/joysofcode/advanced-layouts/commit/951d1b29ba45298a753a27ff5994104901d14066.

**Closed as completed by matiadev** 2023-12-10 17:30 UTC
