### ISSUE TITLE
Conflicting routes error 505

### ISSUE THREAD

**Issue by jahbini** [joysofcode/advanced-layouts#1] opened 2023-09-11 17:29 UTC
I run into this problem every time I try to follow the advanced layout documentation.  Could it be the Mac filesystem?

The client side shows error 505,
The server side says:`
  VITE v4.0.4  ready in 508 ms

  ➜  Local:   http://localhost:5175/
  ➜  Network: use --host to expose
  ➜  press h to show help
The "/" and "/(app)" routes conflict with each other
The "/" and "/(app)" routes conflict with each other
The "/" and "/(app)" routes conflict with each other
The "/" and "/(app)" routes conflict with each other
The "/" and "/(app)" routes conflict with each other
The "/" and "/(app)" routes conflict with each other
1:25:07 PM [vite-plugin-svelte] ssr compile done.
package 	files	  time	   avg
$unknown	    1	30.0ms	30.0ms`

**Comment by matiadev** [comment] 2023-12-10 17:30
The problem was caused by duplicate routes which should be fixed https://github.com/joysofcode/advanced-layouts/commit/951d1b29ba45298a753a27ff5994104901d14066.

**Closed as completed by matiadev** 2023-12-10 17:30 UTC
